#!/bin/sh
echo "Mounted $(pwd) in /mnt, use :l file.hs to load $(pwd)/file.hs"
docker run \
    -it \
    --rm \
    -e "TERM=xterm-256color" \
    --mount type=bind,src=$(pwd),dst=/mnt \
    -w /mnt/ \
    haskell:8 \
    ghci $@
